# Code generated by protoc-gen-twirp_ruby 1.6.0, DO NOT EDIT.
require 'twirp'
require_relative 'things_pb.rb'

class ThingsService < Twirp::Service
  service 'Things'
  rpc :create, ThingParams, ThingResponse, :ruby_method => :create
  rpc :show, ThingParams, ThingResponse, :ruby_method => :show
  rpc :index, ThingFilter, ThingList, :ruby_method => :index
  rpc :update, ThingParams, ThingResponse, :ruby_method => :update
  rpc :destroy, ThingParams, ThingResponse, :ruby_method => :destroy
end

class ThingsClient < Twirp::Client
  client_for ThingsService
end
